# NumPy
Nos va a dar una estructura de datos muy util y eficiente, los arrays.
Estos pueden contener solo un tipo de dato, lo cual los vuelve muy eficientes (cuidado con enteros y floats)


In [ ]:
import numpy as np

Hay distintas formas de crearlos

In [ ]:
array1 = np.array(range(10))
print(array1)

In [ ]:
Np_cero = np.zeros(10)
print(Np_cero)

In [ ]:
Np_cero_int = np.zeros(10, dtype=int)
print(Np_cero_int)

In [ ]:
Np_uno = np.ones(10)
print(Np_uno)


In [ ]:
Np_relleno = np.full(10,256)
print(Np_relleno)

Podemos armar arrays de 2 dimensiones.

Tambien podemos armarlos con numeros "aleatorios"

In [ ]:
arrayBidimensional = np.random.randint(10, size=(3,4))
print(arrayBidimensional)

arrayBidimensional2 = np.random.randint(10, size=(4,6))
print(arrayBidimensional2)

In [ ]:
print(arrayBidimensional[2,3])

# Propiedades de los arrays



In [ ]:
# Dimensiones: con .ndim nos devolvera la cantidad de dimensiones.

print(Np_cero.ndim)

print(arrayBidimensional.ndim)

In [ ]:
# Forma: Podemos ver de que manera se ordenan los datos.

print(arrayBidimensional.shape)

print(arrayBidimensional2.shape)

In [ ]:
# Tamaño: Podemos la cantidad de elementos de un array, es como el .len de las listas

print(Np_cero_int.size)

print(arrayBidimensional.size)


In [ ]:
# Tipo de datos: Podemos ver el tipo de dato que tienen nuestros array (recordemos, solo pueden contener elementos de un tipo)

print(Np_cero.dtype)

print(arrayBidimensional.dtype)


In [ ]:
# Tamaño de elementos: Devuelve el tamaño en bytes de los elementos

print(Np_cero.itemsize)    #En este caso son floats

print(arrayBidimensional.itemsize)     #En este caso son enteros


In [ ]:
# Tamaño total: Bytes totales consumidos en el array

print(arrayBidimensional2.nbytes)

print(Np_cero_int.nbytes)

# Indexado y acceso

Podemos ingresar a los elementos mediante un indice, el cual comienza en 0 y va hasta el ultimo elemento del array.

Podemos acceder a los elementos desde el final con numeros negativos Ej: -1 para el ultimo elemento del array y -2 el penultimo

Para acceder a un elememnto de una matriz debemos indicar fila y columna.


Podemos seleccionar partes del array y separlo del grande. (Debemos marcar desde donde y hasta donde recortar *

    Importante, el 'desde' incluye el valor y el 'hasta' no. (es como si 'desde' fuera <= y 'hasta' > )

In [ ]:
arrayPruebas = np.arange(2,20)
arrayPruebas2D = np.random.randint(10, size=(6,8))
print(arrayPruebas)
print(arrayPruebas2D)

In [ ]:
print(arrayPruebas[9])
print(arrayPruebas[15])

In [ ]:
print(arrayPruebas[-1])
print(arrayPruebas[-3])

In [ ]:
print(arrayPruebas2D[2,0])
print(arrayPruebas2D[1,1])

In [ ]:
print(arrayPruebas2D[1,-2])
print(arrayPruebas2D[1,-1])

In [ ]:
print(arrayPruebas)
print(arrayPruebas2D)

In [ ]:
print(arrayPruebas[2:4])
print(arrayPruebas[4:15])
print(arrayPruebas[4:15:2])

In [ ]:
print(arrayPruebas[:4])
print(arrayPruebas[4:])
print(arrayPruebas[10::2])

In [ ]:
print(arrayPruebas2D[0:4,1:3])

In [ ]:
print(arrayPruebas2D[0::2, :3])

# OPERACIONES BÁSICAS




In [ ]:
probabilidades = np.random.randint(65, size=(8,8))
print(probabilidades)

Reshape

    Como podriamos armar un tablero de ajedrez ?

In [ ]:
ajedrez = np.arange(1,65).reshape(8,8)
print(ajedrez)

Concatenacion: Nos sirve para "pegar" dos arrays, uno al lado del otro.

    Podemos hacerlo de 3 maneras, con .concatenate, con .vstack y con .hstack

In [ ]:
# .concatenate: concatena arrays de una dimension uno a continuacion del otro
Array_1 = np.random.randint(10, size=5)
Array_2 = np.random.randint(10, size=5)
Arrays_concatenados = np.concatenate([Array_1, Array_2])
print(Array_1)
print(Array_2)
print(Arrays_concatenados)

In [ ]:
# .vstack: concatena arrays de manera vertical

print(ajedrez)

ajedrezX2Vertical=np.vstack([ajedrez, ajedrez])
print(ajedrezX2Vertical)

In [ ]:
# .hstack: concatena arrays de manera vertical

print(ajedrez)

ajedrezX2Horizontal=np.hstack([ajedrez, ajedrez])
print(ajedrezX2Horizontal)

Splitting

    Consiste en dividir los arreglos en partes mas pequeñas

In [ ]:
print(Arrays_concatenados)
arrayDividido = np.split(Arrays_concatenados, [3])
print(arrayDividido)

In [ ]:
print(Arrays_concatenados)
arrayDividido = np.split(Arrays_concatenados, [2,5])
print(arrayDividido)

In [ ]:
arrayAlmedio = np.split(Arrays_concatenados, 2)
print(arrayAlmedio)

In [ ]:
primerMitad, segundaMitad = arrayAlmedio
print(primerMitad)
print(segundaMitad)

In [ ]:
# .vsplit: corta arrays de manera vertical

print(ajedrezX2Vertical)


In [ ]:
ajedrez1 , ajedrez2=np.vsplit(ajedrezX2Vertical,[8])
print(ajedrez1)
print(ajedrez2)

In [154]:
# .hsplit: corta arrays de manera vertical

print(ajedrezX2Horizontal)


[[ 1  2  3  4  5  6  7  8  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16  9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56 49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64 57 58 59 60 61 62 63 64]]


In [ ]:
ajedrez1 , ajedrez2=np.hsplit(ajedrezX2Horizontal,[8])
print(ajedrez1)
print(ajedrez2)

In [163]:
array100 = np.random.randint(100, size = (10,10))
print(array100)
print(np.median(array100))

[[30 66 60 39 71 12 46 67  1 26]
 [86 84 36 98 78 13 32 65 63 29]
 [36  1  9 86 66 63 93 17 34 56]
 [ 9 17 87 10 60 51 54 63  0 70]
 [15 55 99 22 64  2 55 28 16 97]
 [71 48 65 14 65 99 17 25 30 15]
 [83 93 53 18 42 94 11 38 56 91]
 [53 52 52 16 20 13 90 88 18 39]
 [91 18 54 16 81 10 81 14 34 92]
 [24 95 51 12 59 72 49 38 34 13]]
50.0
