# Pandas

Estructuras principales

    Objetos Series: Se construyen a partir de listas o numpy arrays, son muy parecidos, solo que tienen indices propios.

In [7]:
import numpy as np
import pandas as pd

In [8]:
numeros = range(0, 5)
numeros_series = pd.Series(numeros)
print(numeros_series)

0    0
1    1
2    2
3    3
4    4
dtype: int64


In [9]:
indices = ['primero', 'segundo', 'tercero', 'cuarto', 'quinto']
numeros_series = pd.Series(numeros, index = indices)
print(numeros_series)

primero    0
segundo    1
tercero    2
cuarto     3
quinto     4
dtype: int64


In [10]:
print(numeros_series.index)
print(numeros_series.values)

Index(['primero', 'segundo', 'tercero', 'cuarto', 'quinto'], dtype='object')
[0 1 2 3 4]


In [11]:
print(numeros_series['primero'])
print(numeros_series[0])

0
0


In [12]:
numeros_series['primero'] = 5
print(numeros_series)

primero    5
segundo    1
tercero    2
cuarto     3
quinto     4
dtype: int64


        Objetos Data Frames: Se los puede pensar como una tabla, algo parecido al los arrays bidimensionales, pero mejores.
        
        Como toda tabla, consta de filas y columnas.
        Cada fila tiene un elemento índice asociado.


In [13]:
modelos = ['A4 3.0 Quattro 4dr manual',
           'A4 3.0 Quattro 4dr auto',
           'A6 3.0 4dr',
           'A6 3.0 Quattro 4dr',
           'A4 3.0 convertible 2dr']
peso = [3583, 3627, 3561, 3880, 3814]
precios = ['$33,430', '$34,480', '$36,640', '$39,640', '$42,490']

autosPeso = pd.Series(peso, index = modelos)
autosPrecios = pd.Series(precios, index = modelos)

print(autosPeso)
print(autosPrecios)

A4 3.0 Quattro 4dr manual    3583
A4 3.0 Quattro 4dr auto      3627
A6 3.0 4dr                   3561
A6 3.0 Quattro 4dr           3880
A4 3.0 convertible 2dr       3814
dtype: int64
A4 3.0 Quattro 4dr manual    $33,430
A4 3.0 Quattro 4dr auto      $34,480
A6 3.0 4dr                   $36,640
A6 3.0 Quattro 4dr           $39,640
A4 3.0 convertible 2dr       $42,490
dtype: object


In [14]:

#print(autos)
autos

Peso   Precio
A4 3.0 Quattro 4dr manual  3583  $33,430
A4 3.0 Quattro 4dr auto    3627  $34,480
A6 3.0 4dr                 3561  $36,640
A6 3.0 Quattro 4dr         3880  $39,640
A4 3.0 convertible 2dr     3814  $42,490

In [15]:
ajedrezAntes = np.arange(1,65).reshape(8,8)
ajedrezAntes

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [16]:
ajedresDF = pd.DataFrame(ajedrezAntes, columns= range(1,9),index=['A','B','C','D','E','F','G','H'])
ajedresDF

1   2   3   4   5   6   7   8
A   1   2   3   4   5   6   7   8
B   9  10  11  12  13  14  15  16
C  17  18  19  20  21  22  23  24
D  25  26  27  28  29  30  31  32
E  33  34  35  36  37  38  39  40
F  41  42  43  44  45  46  47  48
G  49  50  51  52  53  54  55  56
H  57  58  59  60  61  62  63  64

# Seleccion de elementos


En objetos Series

In [17]:
print(numeros_series)

primero    5
segundo    1
tercero    2
cuarto     3
quinto     4
dtype: int64


In [18]:
print(numeros_series['segundo'])

1


In [19]:
print(numeros_series.loc['segundo'])

1


In [20]:
print(numeros_series.iloc[1])    #Este permite unicamente indices numericos

1


En objetos Data Frames

In [21]:
autos

Peso   Precio
A4 3.0 Quattro 4dr manual  3583  $33,430
A4 3.0 Quattro 4dr auto    3627  $34,480
A6 3.0 4dr                 3561  $36,640
A6 3.0 Quattro 4dr         3880  $39,640
A4 3.0 convertible 2dr     3814  $42,490

In [22]:
autos.index

Index(['A4 3.0 Quattro 4dr manual', 'A4 3.0 Quattro 4dr auto', 'A6 3.0 4dr',
       'A6 3.0 Quattro 4dr', 'A4 3.0 convertible 2dr'],
      dtype='object')

In [23]:
autos.columns

#autos['Peso']

Index(['Peso', 'Precio'], dtype='object')

In [24]:
autos.values

array([[3583, '$33,430'],
       [3627, '$34,480'],
       [3561, '$36,640'],
       [3880, '$39,640'],
       [3814, '$42,490']], dtype=object)

In [25]:
#autos.values[1]

autos.loc['A4 3.0 Quattro 4dr auto']

Peso         3627
Precio    $34,480
Name: A4 3.0 Quattro 4dr auto, dtype: object

In [26]:
# Podemos poner condiciones de busqueda, por ejemplo, si queremos el precio de los autos que tengan un peso mayo o igual a 3600


autos.loc[autos.Peso >= 3600, 'Precio']

A4 3.0 Quattro 4dr auto    $34,480
A6 3.0 Quattro 4dr         $39,640
A4 3.0 convertible 2dr     $42,490
Name: Precio, dtype: object

# Operaciones basicas con pandas


Transposicion: Intercambia las filas de un data frame por sus columnas

In [27]:
autos.T

A4 3.0 Quattro 4dr manual A4 3.0 Quattro 4dr auto A6 3.0 4dr  \
Peso                        3583                    3627       3561   
Precio                   $33,430                 $34,480    $36,640   

       A6 3.0 Quattro 4dr A4 3.0 convertible 2dr  
Peso                 3880                   3814  
Precio            $39,640                $42,490

Funciones Vectorizadas: Las funciones de Numpy tambien pueden realizarse sobre Series y Data Frames.
           
           Tras la ejecucion, se conservan los indices

In [28]:
Numeros_en_texto = ['primero','segundo','tercero','cuarto','quinto','sexto','séptimo','octavo','noveno','décimo']

Numeros_2 = range(41,60,2)
Numeros_serie_2 = pd.Series(Numeros_2, index = Numeros_en_texto)
Numeros_serie_2

primero    41
segundo    43
tercero    45
cuarto     47
quinto     49
sexto      51
séptimo    53
octavo     55
noveno     57
décimo     59
dtype: int64

In [29]:
Numeros_3 = range(51,70,2)

Numeros_serie_3 = pd.Series(Numeros_3, index = Numeros_en_texto)
Numeros_serie_3

primero    51
segundo    53
tercero    55
cuarto     57
quinto     59
sexto      61
séptimo    63
octavo     65
noveno     67
décimo     69
dtype: int64

In [30]:
Numeros_serie_3 + 5

primero    56
segundo    58
tercero    60
cuarto     62
quinto     64
sexto      66
séptimo    68
octavo     70
noveno     72
décimo     74
dtype: int64

In [31]:
Numeros_serie_3 / 100

primero    0.51
segundo    0.53
tercero    0.55
cuarto     0.57
quinto     0.59
sexto      0.61
séptimo    0.63
octavo     0.65
noveno     0.67
décimo     0.69
dtype: float64

In [32]:
Numeros_serie_3 * 4

primero    204
segundo    212
tercero    220
cuarto     228
quinto     236
sexto      244
séptimo    252
octavo     260
noveno     268
décimo     276
dtype: int64

In [33]:
Numeros_serie_2 + Numeros_serie_3

primero     92
segundo     96
tercero    100
cuarto     104
quinto     108
sexto      112
séptimo    116
octavo     120
noveno     124
décimo     128
dtype: int64

In [34]:
autos

Peso   Precio
A4 3.0 Quattro 4dr manual  3583  $33,430
A4 3.0 Quattro 4dr auto    3627  $34,480
A6 3.0 4dr                 3561  $36,640
A6 3.0 Quattro 4dr         3880  $39,640
A4 3.0 convertible 2dr     3814  $42,490

In [35]:
autos.Peso * 10

A4 3.0 Quattro 4dr manual    35830
A4 3.0 Quattro 4dr auto      36270
A6 3.0 4dr                   35610
A6 3.0 Quattro 4dr           38800
A4 3.0 convertible 2dr       38140
Name: Peso, dtype: int64

In [36]:
autos.Peso / 100

A4 3.0 Quattro 4dr manual    35.83
A4 3.0 Quattro 4dr auto      36.27
A6 3.0 4dr                   35.61
A6 3.0 Quattro 4dr           38.80
A4 3.0 convertible 2dr       38.14
Name: Peso, dtype: float64

In [37]:
Numeros_serie_2_porcion = Numeros_serie_2[4:7]

Numeros_serie_3_porcion = Numeros_serie_3[5:8]

print(Numeros_serie_2_porcion)

quinto     49
sexto      51
séptimo    53
dtype: int64


In [38]:
print(Numeros_serie_3_porcion)

sexto      61
séptimo    63
octavo     65
dtype: int64


In [39]:
Numeros_serie_2_porcion + Numeros_serie_3_porcion

octavo       NaN
quinto       NaN
sexto      112.0
séptimo    116.0
dtype: float64

In [40]:
Numeros_serie_2_porcion.add(Numeros_serie_3_porcion)

octavo       NaN
quinto       NaN
sexto      112.0
séptimo    116.0
dtype: float64

In [41]:
Numeros_serie_2_porcion.add(Numeros_serie_3_porcion, fill_value=0)

octavo      65.0
quinto      49.0
sexto      112.0
séptimo    116.0
dtype: float64

In [42]:
numerosNaN = Numeros_serie_2_porcion.add(Numeros_serie_3_porcion)
numerosNaN

octavo       NaN
quinto       NaN
sexto      112.0
séptimo    116.0
dtype: float64

In [43]:
# Podemos marcar los NaN con booleanos

numerosNaN.isnull()

octavo      True
quinto      True
sexto      False
séptimo    False
dtype: bool

In [44]:
# Podemos reemplazarlos por lo que queramos

numerosNaN.fillna(0)

octavo       0.0
quinto       0.0
sexto      112.0
séptimo    116.0
dtype: float64

In [45]:
#Podemos quitarlos para que no molesten, aunque a veces es importante tenerlos en cuenta.

numerosNaN.dropna()

sexto      112.0
séptimo    116.0
dtype: float64